name: Go

on:
  push:
    tags: ['v*']

permissions:
  contents: write     #  required for ncipollo/release-action

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:   [linux]
        arch: [amd64, 386, arm64]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build binary
        env:
          GOOS:   ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
        run: |
          mkdir -p dist
          go build -ldflags "-X main.version=${{ github.ref_name }}" \
                  -o dist/ceph_vm_exporter

      - name: Package binary
        run: |
          mkdir -p release
          tar -C dist -czf \
            release/ceph_vm_exporter-${{ github.ref_name }}.${{ matrix.os }}-${{ matrix.arch }}.tar.gz \
            ceph_vm_exporter

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}-${{ matrix.arch }}   # <-- uniq name
          path: release/*.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download ALL artifacts
        uses: actions/download-artifact@v4
        with:
          path: release      # download all  binaries-*-* in this folder

      - run: ls -R release   # проверка

      - name: Create GitHub Release & upload assets
        uses: ncipollo/release-action@v1
        with:
          tag:         ${{ github.ref_name }}
          releaseName: Release ${{ github.ref_name }}
          artifacts:   release/**/*.tar.gz
          token:       ${{ secrets.GITHUB_TOKEN }}
